# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'progress.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSignal

class _Ui_ProgressDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(456, 393)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_1 = QtWidgets.QLabel(Dialog)
        self.label_1.setMinimumSize(QtCore.QSize(80, 0))
        self.label_1.setObjectName("label_1")
        self.gridLayout.addWidget(self.label_1, 0, 0, 1, 1)
        self.progressBar_1 = QtWidgets.QProgressBar(Dialog)
        self.progressBar_1.setProperty("value", 0)
        self.progressBar_1.setObjectName("progressBar_1")
        self.gridLayout.addWidget(self.progressBar_1, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setMinimumSize(QtCore.QSize(80, 0))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.progressBar_2 = QtWidgets.QProgressBar(Dialog)
        self.progressBar_2.setProperty("value", 0)
        self.progressBar_2.setObjectName("progressBar_2")
        self.gridLayout.addWidget(self.progressBar_2, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setMinimumSize(QtCore.QSize(80, 0))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.progressBar_3 = QtWidgets.QProgressBar(Dialog)
        self.progressBar_3.setProperty("value", 0)
        self.progressBar_3.setObjectName("progressBar_3")
        self.gridLayout.addWidget(self.progressBar_3, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setMinimumSize(QtCore.QSize(80, 0))
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.progressBar_4 = QtWidgets.QProgressBar(Dialog)
        self.progressBar_4.setProperty("value", 0)
        self.progressBar_4.setObjectName("progressBar_4")
        self.gridLayout.addWidget(self.progressBar_4, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setMinimumSize(QtCore.QSize(80, 0))
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.progressBar_5 = QtWidgets.QProgressBar(Dialog)
        self.progressBar_5.setProperty("value", 0)
        self.progressBar_5.setObjectName("progressBar_5")
        self.gridLayout.addWidget(self.progressBar_5, 4, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setMinimumSize(QtCore.QSize(80, 0))
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.progressBar_6 = QtWidgets.QProgressBar(Dialog)
        self.progressBar_6.setProperty("value", 0)
        self.progressBar_6.setObjectName("progressBar_6")
        self.gridLayout.addWidget(self.progressBar_6, 5, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setMinimumSize(QtCore.QSize(80, 0))
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 0, 1, 1)
        self.progressBar_7 = QtWidgets.QProgressBar(Dialog)
        self.progressBar_7.setProperty("value", 0)
        self.progressBar_7.setObjectName("progressBar_7")
        self.gridLayout.addWidget(self.progressBar_7, 6, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setMinimumSize(QtCore.QSize(80, 0))
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 7, 0, 1, 1)
        self.progressBar_8 = QtWidgets.QProgressBar(Dialog)
        self.progressBar_8.setProperty("value", 0)
        self.progressBar_8.setObjectName("progressBar_8")
        self.gridLayout.addWidget(self.progressBar_8, 7, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_2.setStretch(0, 8)
        self.verticalLayout_2.setStretch(1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Progress Bar"))
        self.label_1.setText(_translate("Dialog", "Port 1: Progress"))
        self.label_2.setText(_translate("Dialog", "Port 2: Progress"))
        self.label_3.setText(_translate("Dialog", "Port 3: Progress"))
        self.label_4.setText(_translate("Dialog", "Port 4: Progress"))
        self.label_5.setText(_translate("Dialog", "Port 5: Progress"))
        self.label_6.setText(_translate("Dialog", "Port 6: Progress"))
        self.label_7.setText(_translate("Dialog", "Port 7: Progress"))
        self.label_8.setText(_translate("Dialog", "Port 8: Progress"))
        self.pushButton.setText(_translate("Dialog", "Close"))
        
class ProgressDialog(QtWidgets.QDialog, _Ui_ProgressDialog):
    updateRequested = QtCore.pyqtSignal(str, int, int, int, int)

    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi(self)
        self.setModal(False)
        self.setWindowFlags(self.windowFlags() | QtCore.Qt.WindowStaysOnTopHint)
        self.updateRequested.connect(self.update_progress, QtCore.Qt.QueuedConnection)
        self.pushButton.clicked.connect(self.close)

    @QtCore.pyqtSlot(str, int, int, int, int)
    def update_progress(self, bar_type: str, bar_idx: int, percent: int, img_i: int, img_x: int):
        if not (1 <= bar_idx <= 8):
            raise IndexError(f"bar_idx must be between 1 and 8 (got {bar_idx})")
        if not (0 <= percent <= 100):
            raise ValueError("percent must be between 0 and 100")

        getattr(self, f"progressBar_{bar_idx}").setValue(percent)
        if img_i == 0 and img_x == 0:
            getattr(self, f"label_{bar_idx}").setText(f"Port {bar_idx} : " + bar_type)
        else:
            getattr(self, f"label_{bar_idx}").setText(f"Port {bar_idx} ({img_i}/{img_x}): " + bar_type)
            
        if percent == 100 and img_i == img_x:
            getattr(self, f"label_{bar_idx}").setText(f"Port {bar_idx}: Success")
        
    def progress_reset(self):
        for bar_idx in range(1, 9):
            getattr(self, f"progressBar_{bar_idx}").setValue(0)
            getattr(self, f"label_{bar_idx}").setText(f"Port {bar_idx}: Progress")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = ProgressDialog()
    Dialog.show()
    sys.exit(app.exec_())
